class_name SkyCatalog
extends RefCounted
## Generated by tools/textures/fetch_sky.py; don't edit by hand.
## Per sky (assets/textures/sky/sky_<key>.jpg): `energy` scales the stored
## 0-1 texture so the sky's median brightness is 1.0; the sun's azimuth
## (radians, 0 = toward -Z, + toward +X) and elevation (degrees) as
## photographed; its colour; the average horizon (0-6° up, away from the
## sun) and zenith colours, linear, relative to the median.

const SKIES := {
	"dawn": {"energy": 19.6106, "sun_az": 0.6288, "sun_el": 2.15, "sun_color": Color(1.000, 0.113, 0.000),
		"horizon": Color(1.5142, 1.3239, 1.2567), "zenith": Color(0.4882, 0.7301, 1.1803)},
	"morning": {"energy": 34.8501, "sun_az": 0.6264, "sun_el": 37.98, "sun_color": Color(1.000, 0.962, 0.872),
		"horizon": Color(1.5936, 1.6864, 1.7767), "zenith": Color(0.5404, 0.7320, 1.0806)},
	"day": {"energy": 18.1995, "sun_az": 0.5973, "sun_el": 47.92, "sun_color": Color(0.967, 1.000, 0.930),
		"horizon": Color(1.0386, 1.0972, 1.3442), "zenith": Color(1.3524, 1.4926, 1.9625)},
	"sunset": {"energy": 24.6672, "sun_az": 0.6869, "sun_el": 6.90, "sun_color": Color(1.000, 0.545, 0.168),
		"horizon": Color(1.3450, 1.3329, 1.3400), "zenith": Color(0.4334, 0.6697, 1.1216)},
	"dusk": {"energy": 7.0836, "sun_az": 0.6248, "sun_el": 16.66, "sun_color": Color(1.000, 0.571, 0.578),
		"horizon": Color(0.8940, 0.7150, 0.9565), "zenith": Color(0.7677, 0.8679, 1.5117)},
	"night": {"energy": 36.5276, "sun_az": 0.6290, "sun_el": 13.83, "sun_color": Color(1.000, 0.777, 0.621),
		"horizon": Color(3.1415, 3.7111, 4.0307), "zenith": Color(0.4024, 0.7322, 1.3163)},
}
